### ISSUE TITLE
update any links pointing to charters-qa site

### ISSUE THREAD

**Issue by holfordm** [bodleian/charters#101]
to be done at launch

**Comment by holfordm** [comment]
fixed by commit above

**Comment by holfordm** [comment]
@irv or @Slange-Mhath it would be great if you could re-index with this change as currently the "browse" links on the collections pages lead to the qa site with the very different style of previews

**Comment by irv** [comment]
Doing it now - there's a nested comment in tei-qa/MSS_Ch_Oxon/MS_Ch_Oxon_a_62_fol_14.xml which is invalid btw
