### ISSUE TITLE
`condition` in `seal`: do not display as a header

### ISSUE THREAD

**Issue by holfordm** [bodleian/charters#102]
(for e.g. of current display see https://charters-qa.bodleian.ox.ac.uk/catalog/charter_100031 )

**Comment by Slange-Mhath** [comment]
Hey @holfordm if you don't want it to be a heading (h4) would you want it to be in bold (<b>) or just displayed normally? I have to say I think semantically it makes sense that it is an h4 as it is a subheading of the Phyiscal description, which is then followed by a list. I agree though that it looks a bit odd. I guess thats something we'd need to change in the data @irv ?

**Comment by irv** [comment]
Are we talking about this?

![image](https://github.com/bodleian/charters/assets/390869/6159e18e-cf24-4941-8c41-40248a2df2cc)

<img width="311" alt="image" src="https://github.com/bodleian/charters/assets/390869/e1c07996-ffd4-470e-a05e-6812c3fe4fd8">

**Comment by Slange-Mhath** [comment]
I think so - yes. But @holfordm might be able to clarify.
