### ISSUE TITLE
older-style links in `bibl/@facs`

### ISSUE THREAD

**Issue by holfordm** [bodleian/charters#107]
@irv , there are a number of records with older style links in `additional//source//bibl/@facs` in the form `\d\d_\d\d\d\d\d\.tif` - some of these due to errors in the format [fixed by 4c85aec1a2b5cbdd463b61f6f1edb709298229af] but some where I can't see why the reference hasn't matched. (E.g. MS. Ch. Oxon. 2006, 2050 etc. -- all the cases seem to involve vol. 23 of the slip images)

relatedly - what should be the procedure for future additions to the catalogue where we need to convert older style tif references to the new style iiif references?

**Comment by irv** [comment]
that's odd because vol 23 didn't have any renumbering. I'll have a look
