### ISSUE TITLE
"display 200 items per page" only displays 100

### ISSUE THREAD

**Issue by holfordm** [bodleian/charters#108]
e.g. https://charters-qa.bodleian.ox.ac.uk/?f%5Bms_collection_s%5D%5B%5D=D.D.+Weld&f%5Btype%5D%5B%5D=charter&per_page=200 
Not a big problem if 100 is actually the maximum.

**Comment by Slange-Mhath** [comment]
Ooops, I didn't realise that - good catch. I guess 200 is a bit too much, shall I just take that out of the pagination so that we have 25,50,100 instead? I think thats more than enough anyway?

**Comment by holfordm** [comment]
Agreed!
