### ISSUE TITLE
sorting of results

### ISSUE THREAD

**Issue by holfordm** [bodleian/charters#118]
I think this is currently done according to xml:id / url - it would be more logical have have an alphanumeric sort if possible

**Comment by irv** [comment]
e.g.

``` <place type="place" xml:id="place_111086">
               <placeName type="index"/>
               <placeName type="formInDocument"/>
               <region type="parish"/>
               <region type="county" key="place_000040">Lincolnshire</region>
               <idno/>
               <note type="charter"/>
            </place>
```

**Comment by holfordm** [comment]
should be fixed by e05da59d7c381ffbf7a908ca84287e79ca20ef1d

**Comment by holfordm** [comment]
sorting in charters runs 1, 10, 11, which may be unavoidable (?), but 1, 2, 3, ... 10, 11 would be preferable if possible

**Comment by Slange-Mhath** [comment]
seems like thats solved in the other catalogues through a sort_title field, which seems to work well for charters too. Will commit and push to QA.

**Comment by Slange-Mhath** [comment]
Let me know if you are happy with that, and I can deploy it on live too maybe?
