### ISSUE TITLE
MS. Rolls Heref 41

### ISSUE THREAD

**Issue by holfordm** [bodleian/charters#119]
New record needs to be created https://babel.hathitrust.org/cgi/pt?id=mdp.39015024908256&seq=414

**Comment by irv** [comment]
Both MS. Rolls Heref 40 and MS. Rolls Heref 41 have the same id:

../tei-qa/MSS_Ch_Heref/MS_Rolls_Heref_40.xml
1:<?xml-model href="https://raw.githubusercontent.com/bodleian/CEI2TEI/master/tei_cei.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?><TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="charter_318037">

../tei-qa/MSS_Ch_Heref/MS_Rolls_Heref_41.xml
1:<?xml-model href="https://raw.githubusercontent.com/bodleian/CEI2TEI/master/tei_cei.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?><TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="charter_318037">
