### ISSUE TITLE
send orderable item shelfmarks to Aeon

### ISSUE THREAD

**Issue by holfordm** [bodleian/charters#127]
colleagues in the reading room have requested that the main shelfmark sent to Aeon for the stack team to fetch should be the orderable item as well as, or instead of, the individual charter shelfmark. Ideally one value would be sent as the shelfmark and the other value in the "Notes" field. Is something like this possible? It is quite high priority as finding the orderable item is a significant additional burden for stack staff. 

possible related data issue for @holfordm #90

**Comment by holfordm** [comment]
@irv I have added `idno type=orderableItem` to all relevant records, I think, so as with #56 the ordering system as set up on QA can be moved over to production when you have a chance.

**Comment by irv** [comment]
This should be enabled now (and reindexed with the latest data)
